name: release
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Run tests
      if: matrix.os == 'windows-latest'
      run: go test -race ./...

    - name: Build and publish
      run: rake build

    # - name: Archive action artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: artifacts
    #     path: build/artifacts/*

    - name: Upload artifacts to release
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/artifacts/*"
        bodyFile: "build/release_notes"
        token: ${{ secrets.GITHUB_TOKEN }}
