name: release
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Check version
        run: go version

      - name: Test and build
        run: rake build

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          flags: unittests
          file: build/go-test-coverage.txt

      - name: Archive build artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{env.VERSION}}
          path: |
            build/release_notes.md
            build/artifacts/*

      - name: Upload artifacts to release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/artifacts/*"
          bodyFile: "build/release_notes.md"
          token: ${{ secrets.GITHUB_TOKEN }}
